### ISSUE TITLE
farm summary?

### ISSUE THREAD

**Issue by ilmerovingio** [bpx-network/bpx-beacon-client#1]
root@n01:~# sudo -u bpx /usr/bin/bpx farm summary
Traceback (most recent call last):
  File "bpx/cmds/bpx.py", line 129, in <module>
  File "bpx/cmds/bpx.py", line 125, in main
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "bpx/cmds/farm.py", line 54, in summary_cmd
ModuleNotFoundError: No module named 'bpx.cmds.farm_funcs'
[3703534] Failed to execute script 'bpx' due to unhandled exception!

**Comment by bpx-chain** [comment]
Fixed in 3.0.1
