### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by ShrektacularSwamp** [bpx-network/bpx-beacon-client#3]
Trying to install on Ubuntu 22.04. Installed both the Beacon and the Execution from latest .deb files.
When I try to launch via GUI it just spins wheels forever trying to load configuration, and when I try to launch via CLI it gives me a bunch of traceback errors:

Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "bpx/cmds/bpx.py", line 129, in <module>
  File "bpx/cmds/bpx.py", line 125, in main
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "bpx/cmds/bpx.py", line 104, in run_daemon_cmd
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "bpx/daemon/server.py", line 1399, in async_run_daemon
  File "bpx/daemon/server.py", line 142, in __init__
  File "bpx/server/server.py", line 57, in ssl_context_for_server
  File "ssl.py", line 791, in _create_unverified_context
FileNotFoundError: [Errno 2] No such file or directory
[1764387] Failed to execute script 'bpx' due to unhandled exception!
Daemon not started yet
Failed to create the bpx daemon

What's up with this? All the prior versions do this also.

**Comment by bpx-chain** [comment]
Does the problem occur every time you launch the GUI? This issue is known to us, but only on first run right after installation.

What CLI command are you using to launch the GUI?

**Comment by bpx-chain** [comment]
Closing due to no response
